### ISSUE TITLE
Proposal: add blog links to the sections

### ISSUE THREAD

**Issue by lholmquist** [nodeshift/nodejs-reference-architecture#105]
Currently we only have a link to the introduction of the blog series on the main readme

> If you want to learn more about some of the discussions that went into the Node.js reference architecture you can check out the [Introduction to the Node.js reference architecture](https://developers.redhat.com/blog/2021/03/08/introduction-to-the-node-js-reference-architecture-part-1-overview) blog post series.

This is a proposal to also add the relevant blog links to their sections.  Perhaps in a "further reading section"

**Comment by mhdawson** [comment]
If we add them to the specific docs I think we'll want a common section that is present in all of the sections.
