### ISSUE TITLE
Formatting of the docs into the website. 

### ISSUE THREAD

**Issue by wtrocki** [nodeshift/nodejs-reference-architecture#11]
Hi

I have been using docusaurus in couple places and it actually enables using some nice syntax highlighting in markdown. What will be the considered target platform for the publishing of this documentation? If we would consider docusaurus I have some experience with setting this up and can help to drive it.

**Comment by mhdawson** [comment]
I don't have any preconceived notion of what we should use to improve the readability. It seems like a reasonable option if the the rest of the team agrees.

**Comment by wtrocki** [comment]
@mhdawson What I can do is to create prototype of the website. 
Example website
https://graphback.dev

We can have documentation and some of the node.js logos. If you thing that having prototype website will be easier to get backing for it on the call let me know. I can do some quick prototype.

**Comment by wtrocki** [comment]
Prototype #15 
Blocker #14

**Comment by wtrocki** [comment]
Will be solved by docusaurus CI/CD

**Comment by mhdawson** [comment]
I think we can close this since we have the website being build with Docusaurus. Closing. @wtrocki let me know if you think that was not the right thing to do.
