### ISSUE TITLE
Moving all md files into docs folder.

### ISSUE THREAD

**Issue by wtrocki** [nodeshift/nodejs-reference-architecture#14]
When using some builders etc. it will be needed to move all MD files int some folder. Currently they are in the root which will make it hard to differentiate with some others like license/contributing etc. I'm happy to do that as requirement to build docusaurus prototype website for this engagement.

**Comment by mhdawson** [comment]
I assume the README.md that has the current table of contents would stay at the top level right ?

**Comment by wtrocki** [comment]
Yes. That will stay and when working with docusaurus or any website toc will be generated from files in doc folder etc.

**Comment by lholmquist** [comment]
closing.  addressed in #27
