### ISSUE TITLE
Recommend internal npm repo process

### ISSUE THREAD

**Issue by joesepi** [nodeshift/nodejs-reference-architecture#42]
This question was raised in a recent talk Michael and I gave internally at IBM:

>Has there been any progress on an internal NPM repo that hosts only approved & validated packages and versions so that every BU didn't have to sort this on their own - this would go a long way to help developers get consistency across a company. It would also help with security.

**Comment by joesepi** [comment]
I see it mentioned in the list of resources, so feel free to delete this issue. I just wanted to make sure it was captured from the conversation. Thanks.

**Comment by mhdawson** [comment]
Thanks, closing.
