### ISSUE TITLE
Oauth2 vs Auth Code Workflow

### ISSUE THREAD

**Issue by strangiato** [nodeshift/nodejs-reference-architecture#45]
Reading through the documentation the following line from the [auth section](https://github.com/nodeshift/nodejs-reference-architecture/blob/main/docs/functional-components/auth.md) doesn't make a whole lot of sense:

> Do not use OAUTH2 implicit grant, is preferred to use Authorization code workflow.

I'm not sure if I should be reading this as 

> Do not use OAUTH2 implicit grant, however, it is preferred to use instead of Authorization code worflow.

Or if there is something else missing from that sentence.

**Comment by mhdawson** [comment]
@strangiato thanks for the ping, just catching up and will try to take a look soon.

**Comment by mhdawson** [comment]
@strangiato sorry it took me so long to get to this.  Have submitted this PR to address - https://github.com/nodeshift/nodejs-reference-architecture/pull/48

**Comment by lholmquist** [comment]
closed via 6e28cdf4946367db71b14ff61d500640553e48a0
