### ISSUE TITLE
Request for addition - GraphQL - @octokit/graphql 

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/nodejs-reference-architecture#47]
Hi @wtrocki we are using this module https://www.npmjs.com/package/@octokit/graphql
which is a `well-known-github-api-graphql-module`. 
also used in other organizations, for example https://github.com/search?q=org%3Apkgjs+octokit&type=code

Can you please add this module to the GraphQL section?
thanks

**Comment by wtrocki** [comment]
I do not see the reason for it. That library is just for the github API/specifics. Would we add every possible graphql API?

**Comment by helio-frota** [comment]
>...  to build their own graphql api

Sorry for my lack of info, in fact, I personally never used GraphQL technology before.
But I got what you mean. By reading again the spec:

"Our target will be to provide comprehensive set of the tools to add graphql support for both client and server side applications"

"...Exposes GraphQL" 
"...Builds GraphQL schema"
"...Prevents from overfetching data"
"...Compiles graphql schema"
...

And the clients mentioned there, are "general" clients right?

That makes sense thanks for the response. :+1:

**Comment by wtrocki** [comment]
Github, AWS etc. have graphql api but there is no value on us picking the package because there will be only single package for those from official vendors. Reference spec generally is to be reffere to pick tools where more options are needed.
