### ISSUE TITLE
[Feedback] Define tools for grapql for rate limiting, complexity and monitoring 

### ISSUE THREAD

**Issue by wtrocki** [nodeshift/nodejs-reference-architecture#56]
Reference for GraphQL is missing useful elements outside GraphQL that require GraphQL to be used.

- rate limiting, 
- complexity
-  monitoring  

All of those are specific to GraphQL

CC @mhdawson

**Comment by mhdawson** [comment]
@wtrocki I think you covered this in https://github.com/nodeshift/nodejs-reference-architecture/pull/57, right?
