### ISSUE TITLE
Move Helmet.js to security 

### ISSUE THREAD

**Issue by upkarlidder** [nodeshift/nodejs-reference-architecture#62]
`Helmet.js` is currently listed under `Authentication and Authorization`. I just checked their docs, and they provide good security HTTP headers. Should it not move to security? I don't see a security section in `functional components`. There is one in `Development`.

**Comment by mhdawson** [comment]
We do have that recommendation in https://github.com/nodeshift/nodejs-reference-architecture/blob/main/docs/functional-components/webframework.md, maybe we should just remove from `Authentication and Authorization` as it is an Express specific recommendation.

**Comment by upkarlidder** [comment]
+1 for removing from `Authentication and Authorization` or link back to the `web framework` section.

**Comment by mhdawson** [comment]
PR to address this -https://github.com/nodeshift/nodejs-reference-architecture/compare/main...remove-helmet-auth?quick_pull=1

**Comment by mhdawson** [comment]
PR landed, closing
