### ISSUE TITLE
Research on static file/serving platforms

### ISSUE THREAD

**Issue by wtrocki** [nodeshift/nodejs-reference-architecture#9]
Hi

I have done some preliminary work to seed discussion on static middlewares in Node.js.

I think we can have 3 categories for those:

- InApp
This is represented usually by underlying HTTP API. To name few examples:
https://expressjs.com/en/starter/static-files.html
https://www.tutorialsteacher.com/nodejs/serving-static-files-in-nodejs
https://nodejs.org/en/knowledge/HTTP/servers/how-to-serve-static-files/

- Cloud (requires connectors like AWS S3 etc.)
This is what red hat is actually using in java frameworks a lot: 
https://quarkus.io/guides/amazon-s3

- Kubernetes (hybrid cloud solutions) that are s3 compatible - https://www.gluster.org/
This is red hat one: https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/3.11/html/operations_guide/s3_object_store

Generally s3 dominating as a store.

There is also concept how to actually reference and store s3 files with auth in database but this is very specific and it is easier to google it rather than reference it here.

@mhdawson This might actually require some discussion on call.

**Comment by wtrocki** [comment]
Include deployment of the app that is changed - cache invalidation issue.

**Comment by roastlechon** [comment]
Using bundler to produce static assets with hash in filename.
AND/OR
Using version in path of static asset so new version of Node app (serving the assets) will not result in poisoned/old cache of assets.

**Comment by wtrocki** [comment]
Done in #13
